# Generated by Django 4.2.2 on 2023-07-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('mobile_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('roll_no', models.CharField(max_length=50)),
            ],
        ),
    ]
