# Generated by Django 4.2.2 on 2023-07-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_address_student_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
